project_id = "pqlnrobcadqgpfuahoqw"

[functions.aria-chat]
verify_jwt = false

[functions.send-2fa-code]
verify_jwt = false

[functions.send-payment-reminders]
verify_jwt = false

[functions.send-order-whatsapp]
verify_jwt = false
